### PR TITLE
Remove hasher bound on map and set ser/de

### PR DESCRIPTION
**Pull request by austinabell**

### CODE REVIEW

**Comment by austinabell** [comment]
Also fixed nostd for pubkey, let me know if you want me to separate and put into a diff PR

**Comment by armaniferrante** [comment]
Closing as mentioned by https://github.com/project-serum/anchor/pull/103.

**Comment by austinabell** [comment]
Oh this was good to come in as is, it only unconstrains the generic bound on serialization (brought into near upstream already) and fixes nostd. Only the other PR was unfinished, but feel free to leave this closed if you like

**Comment by armaniferrante** [comment]
My bad! @austinabell I'll just merge upstream into here. Can you open a separate PR for the pubkey changes?

**Pull request closed without merging**
